# Sentinel 2 Demo - Kenya

The following notebook demonstrates how to access Sentinel 2 data using the Planet OS API. Note that the data and API endpoints used in this notebook are intended to be used for demonstration purposes only, and may be updated or removed without notice.

We'll be working with two Sentinel 2 datasets from the Planet OS Datahub, [RGB bands](http://data.planetos.com/datasets/sentinel2_kenya_clouds_rgb) and an [NDVI](http://data.planetos.com/datasets/sentinel2_kenya_clouds_ndvi) product calculated by Planet OS. Both datasets provide spatial coverage in Kenya, include cloud coverage percentages, and have had a cloud mask applied to remove cloudy data points.

If you'd prefer to work with the original data that includes clouds, you can replace the Planet OS dataset IDs used later in this notebook accordingly:

* sentinel2_kenya_clouds_rgb => [sentinel2_kenya_rgb](http://data.planetos.com/datasets/sentinel2_kenya_rgb)
* sentinel2_kenya_clouds_ndvi => [sentinel2_kenya_ndvi](http://data.planetos.com/datasets/sentinel2_kenya_ndvi)

In [1]:
%matplotlib inline

import folium
import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
import dateutil.parser
from shapely.geometry import Point
import simplejson as json
from urllib.parse import urlencode
from urllib.request import urlopen, Request

A Planet OS API key is required to run this notebook. Keys are displayed in the [account settings](http://data.planetos.com/account/settings/) page on the Planet OS Datahub. If you do not have a Planet OS account, you can [sign up for free](http://data.planetos.com/plans).

In [2]:
apikey = 'YOUR-API-KEY-GOES-HERE'

## API Queries

Below we setup some query functions using the Planet OS API.

We'll be using two API endpoints, the Dataset endpoint to query for metadata and available variables, and the Point endpoint to query for actual data. We recommend reviewing the [API documentation](http://docs.planetos.com/#rest-api-v1) for more details on response format and available query parameters.

Note that we'll also be using some undocumented features in this demo, so the required endpoints may change in the future as features such as polygon selection evolve.

In [3]:
def api_query(url):
#     print("API Url: %s" % url) # debug helper: display API urls in output
    request = Request(url)
    response = urlopen(request)
    return json.loads(response.read())

def api_dataset_query(id, params):
    '''
    Queries the Planet OS API dataset endpoint and returns the
    response as a JSON object.
    id (str): Planet OS dataset ID
    params (dict): Dict of API query parameters
    '''
    query = urlencode(params)
    url = "http://api.planetos.com/v1/datasets/%s?%s" % (id, query)
    return api_query(url)

def api_point_query(id, params):
    '''
    Queries the Planet OS API point endpoint and returns the
    response as a JSON object.
    
    id (str): Planet OS dataset ID
    params (dict): Dict of API query parameters
    '''
    query = urlencode(params)
    url = "http://api.planetos.com/v1/datasets/%s/point?%s" % (id, query)
    return api_query(url)

## Dataset Metadata

Let's query the API for the RGB and NDVI datasets and display some information about them.

In [4]:
# The Planet OS dataset ids are required in the query string.
# Dataset IDs can be found on the dataset detail pages in the right-hand
# data access column once a user has authenticated.
ds_rgb_id = 'sentinel2_kenya_clouds_rgb'
ds_ndvi_id = 'sentinel2_kenya_clouds_ndvi'

# All queries require a valid API key
params = {'apikey': apikey, }

# Query the dataset endpoint for both RGB and NDVI
ds_rgb_json = api_dataset_query(ds_rgb_id, params)
ds_ndvi_json = api_dataset_query(ds_ndvi_id, params)

In [5]:
# Let's summarize the results in ASCII
def ds_summary(ds):
    '''
    Prints a summary of a dataset including title, variable names,
    variable long names, and unit.
    
    ds (json): Planet OS API dataset response in JSON format
    '''
    print(ds['Title'])
    print('-' * 80)
    print("{0:<30} {1:<40} {2:<10}".format("Variable", "Long Name", "Unit"))
    print('-' * 80)
    for v in ds['Variables']:
        name = v['name'] or '-'
        long_name =  v['longName'] or '-'
        unit = v['unit'] or '-'
        print("{0:<30} {1:<40} {2:<10}".format(name, long_name, unit))

ds_summary(ds_rgb_json)
print()
ds_summary(ds_ndvi_json)

Sentinel2 RGB (Kenya)
--------------------------------------------------------------------------------
Variable                       Long Name                                Unit
--------------------------------------------------------------------------------
blue                           Band 2 blue                              -
lon                            longitude                                degrees_east
green                          Band 3 green                             -
context_time_lat_lon           -                                        -
mx_dataset                     -                                        -
crs                            -                                        -
lat                            latitude                                 degrees_north
cloudy_pixels_percentage       cloudy_pixels_percentage                 percentage
red                            Band 4 red                               -
time                           Time                                     microseconds since 1970-01-01 00:00:00
context_time                   -                                        -

Sentinel2 NDVI (Kenya)
--------------------------------------------------------------------------------
Variable                       Long Name                                Unit
--------------------------------------------------------------------------------
lon                            longitude                                degrees_east
ndvi                           Normalized Difference Vegetation Index   -
context_time_lat_lon           -                                        -
mx_dataset                     -                                        -
crs                            -                                        -
lat                            latitude                                 degrees_north
cloudy_pixels_percentage       cloudy_pixels_percentage                 percentage
time                           Time                                     microseconds since 1970-01-01 00:00:00
context_time                   -                                        -

## Requesting RGB Data at a Point

From the output above, we can see the available variables. Variable names can be used with the `var` parameter to request values for just one or more (comma separated) variables within the dataset.

Let's request RGB values using the Point endpoint from the Sentinel-2 RGB (Kenya) dataset at the nearest available point from a specific coordinate.

In [6]:
# Select a point in decimal degrees to query. We'll use the centroid of a farm in Kenya.
# This particular point is interesting because it falls within 4 unique Sentinel 2
# grid tiles. As a result, our response will return values from each of the 4 tiles.
lon = 36.62117917585404
lat = -0.9584909201199898

params = {'apikey': apikey, # always required
          'count': 1, # number of values to return per classifier (e.g. tile)
          'lat': lat, # latitude of interest
          'lon': lon, # longitude of interest
          'max_count': 'true', # return total count of available values
          'nearest': 'true', # return data from the nearest available point
          'time_order': 'desc', # return data in descending chronological order
          'var': 'red,green,blue', # return red, green and blue variables
         }

ds_rgb_point = api_point_query(ds_rgb_id, params)
# print(json.dumps(ds_rgb_point, indent=2))

In [7]:
# The raw response contains two top level elements: 'entries' which contains the values
# and 'stats' which contains some metadata about the values. We'll create a Pandas
# dataframe with the values in 'entries'.

df = pd.io.json.json_normalize(ds_rgb_point['entries'])
print(df.count())
df.head()

axes.latitude       4
axes.longitude      4
axes.time           4
classifiers.tile    4
context             4
data.blue           2
data.green          2
data.red            2
dtype: int64

,axes.latitude,axes.longitude,axes.time,classifiers.tile,context,data.blue,data.green,data.red
0,-0.958516,36.621220,2016-08-15T08:08:34,36MZE,time_lat_lon,NaN,NaN,NaN
1,-0.958492,36.621159,2016-08-12T07:57:10,37MBV,time_lat_lon,14153.0,12845.0,11983.0
2,-0.958452,36.621212,2016-08-15T08:08:34,36MZD,time_lat_lon,NaN,NaN,NaN
3,-0.958468,36.621216,2016-08-12T07:57:10,37MBU,time_lat_lon,14574.0,13190.0,12168.0

The query above requested the most recent values at a point nearest our coordinate of interest. The response values are shown with their repective axes (`axes.latitude`, `axes.longitude`, and `axes.time`), as well as the tile (`classifiers.tile`) the value was sourced from.

Now depending on _when_ this query was performed, there may have been sufficient cloud cover to prevent the acquisition of data in the RGB bands. This would result in `NaN` values for the `data.blue`, `data.green`, and `data.red` variables.

If instead we wanted to gather the last four passes instead of the most recent pass, we can do so using the `count` parameter.

In [8]:
# Let's increase the value count per tile to 5.
# Note that we could also use the maxCount value to acquire all available values as well.
# params['count'] = ds_rgb_point['stats']['maxCount']
params['count'] = 5

ds_rgb_point = api_point_query(ds_rgb_id, params)

In [9]:
df = pd.io.json.json_normalize(ds_rgb_point['entries'])
print(df.count())
df.head()

axes.latitude       17
axes.longitude      17
axes.time           17
classifiers.tile    17
context             17
data.blue           10
data.green          10
data.red            10
dtype: int64

,axes.latitude,axes.longitude,axes.time,classifiers.tile,context,data.blue,data.green,data.red
0,-0.958516,36.62122,2016-08-15T08:08:34,36MZE,time_lat_lon,NaN,NaN,NaN
1,-0.958516,36.62122,2016-08-12T07:57:10,36MZE,time_lat_lon,13241.0,12131.0,11451.0
2,-0.958516,36.62122,2016-08-05T08:03:48,36MZE,time_lat_lon,NaN,NaN,NaN
3,-0.958516,36.62122,2016-08-02T07:55:56,36MZE,time_lat_lon,167.0,384.0,441.0
4,-0.958516,36.62122,2016-07-26T08:06:25,36MZE,time_lat_lon,NaN,NaN,NaN

Let's cleanup the `NaN` values and use the `describe()` method to print some stats about the data.

In [10]:
# drop NaN values and save as clean dataframe
df_clean = df.dropna()

# index by time using the axes.time column and sort descending
pd.to_datetime(df_clean["axes.time"])
df_clean.set_index('axes.time', inplace=True)
df_clean = df_clean.sort_index(ascending=False)

print(df_clean.describe())
df_clean.head()

       axes.latitude  axes.longitude     data.blue   data.green      data.red
count      10.000000       10.000000     10.000000     10.00000     10.000000
mean       -0.958482       36.621199   5852.800000   5426.60000   5052.200000
std         0.000024        0.000028   7217.431842   6442.11051   5972.401542
min        -0.958516       36.621159    167.000000    384.00000    357.000000
25%        -0.958492       36.621172    262.000000    437.00000    425.250000
50%        -0.958480       36.621214    344.500000    505.00000    486.500000
75%        -0.958468       36.621216  13925.000000  12666.50000  11850.000000
max        -0.958452       36.621220  14929.000000  13441.00000  12344.000000

,axes.latitude,axes.longitude,classifiers.tile,context,data.blue,data.green,data.red
axes.time,,,,,,,
2016-08-12T07:57:10,-0.958516,36.621220,36MZE,time_lat_lon,13241.0,12131.0,11451.0
2016-08-12T07:57:10,-0.958492,36.621159,37MBV,time_lat_lon,14153.0,12845.0,11983.0
2016-08-12T07:57:10,-0.958452,36.621212,36MZD,time_lat_lon,14929.0,13441.0,12344.0
2016-08-12T07:57:10,-0.958468,36.621216,37MBU,time_lat_lon,14574.0,13190.0,12168.0
2016-08-02T07:55:56,-0.958516,36.621220,36MZE,time_lat_lon,167.0,384.0,441.0

## Additional API Query Parameters

The code below highlights some additional parameters that can be used in an API query.

* `buffer` is used to query a bounding box around the point of interest. The value is expressed in decimal degrees.
* `classifier:tile` can be used to request data from a single Sentinel-2 tile.
* `grouping` is used to compact data values along a particular axis. Currently we support the `location` value, which will return an array of values with indices corresponding to the latitude and longitude axes.

Let's use a combination of these parameters to request a compact response of data from the `37MBU` tile that resides within `0.001` degrees of our latitude and longitude.

In [11]:

params_compact = {'apikey': apikey, # always required
                  'buffer': 0.001, # return data from all points within 0.001 degree bounding box centered on lat/lon
                  'classifier:tile': '37MBU', # only return values from 37MBU tile
                  'count': 10, # number of values to return per classifier (e.g. tile)
                  'grouping': 'location', # compact into 2-d array by location axis (lat/lon)
                  'lat': lat, # latitude of interest
                  'lon': lon, # longitude of interest
                  'time_order': 'desc', # return data in descending chronological order
                  'var': 'red,green,blue', # return red, green and blue variables
                 }
ds_rgb_point_compact = api_point_query(ds_rgb_id, params_compact)
print(json.dumps(ds_rgb_point_compact))

{"entries": [{"indexAxes": [["latitude", [-0.9594591856002808, -0.9593690633773804, -0.95927894115448, -0.9591888189315796, -0.9590986967086792, -0.9590085744857788, -0.9589184522628784, -0.958828330039978, -0.9587382078170776, -0.9586480855941772, -0.9585579633712769, -0.9584679007530212, -0.9583777785301208, -0.9582876563072205, -0.9581975340843201, -0.9581074118614197, -0.9580172896385193, -0.9579271674156189, -0.9578370451927185, -0.9577469229698181, -0.9576568007469177, -0.9575666785240173]], ["longitude", [36.62022399902344, 36.62031555175781, 36.62040710449219, 36.6204948425293, 36.62058639526367, 36.62067794799805, 36.620765686035156, 36.62085723876953, 36.62094497680664, 36.621036529541016, 36.62112808227539, 36.6212158203125, 36.621307373046875, 36.62139892578125, 36.62148666381836, 36.621578216552734, 36.621665954589844, 36.62175750732422, 36.621849060058594, 36.6219367980957, 36.62202835083008, 36.62211990356445]]], "data": {"green": [[13694.0, 13655.0, 13607.0, 13668.0, 13726.0, 13731.0, 13716.0, 13778.0, 13746.0, 13665.0, 13694.0, 13631.0, 13592.0, 13587.0, 13539.0, 13368.0, 13370.0, 13298.0, 13048.0, 13194.0, 13226.0, 13150.0], [13770.0, 13666.0, 13627.0, 13661.0, 13742.0, 13715.0, 13744.0, 13755.0, 13804.0, 13707.0, 13646.0, 13624.0, 13587.0, 13579.0, 13433.0, 13185.0, 13229.0, 13192.0, 13077.0, 13138.0, 13175.0, 13125.0], [13768.0, 13715.0, 13670.0, 13607.0, 13716.0, 13737.0, 13731.0, 13805.0, 13759.0, 13720.0, 13685.0, 13704.0, 13674.0, 13633.0, 13390.0, 13200.0, 13309.0, 13253.0, 13153.0, 13137.0, 13148.0, 13088.0], [13770.0, 13676.0, 13642.0, 13707.0, 13707.0, 13720.0, 13744.0, 13757.0, 13718.0, 13676.0, 13650.0, 13711.0, 13700.0, 13576.0, 13329.0, 13261.0, 13333.0, 13350.0, 13240.0, 13270.0, 13240.0, 13142.0], [13709.0, 13690.0, 13731.0, 13752.0, 13715.0, 13718.0, 13739.0, 13666.0, 13637.0, 13587.0, 13531.0, 13609.0, 13733.0, 13615.0, 13379.0, 13329.0, 13337.0, 13366.0, 13320.0, 13257.0, 13233.0, 13205.0], [13642.0, 13679.0, 13739.0, 13807.0, 13776.0, 13698.0, 13696.0, 13605.0, 13676.0, 13596.0, 13574.0, 13598.0, 13668.0, 13509.0, 13394.0, 13316.0, 13348.0, 13383.0, 13318.0, 13279.0, 13250.0, 13161.0], [13672.0, 13670.0, 13728.0, 13798.0, 13768.0, 13676.0, 13657.0, 13653.0, 13589.0, 13550.0, 13615.0, 13620.0, 13654.0, 13528.0, 13387.0, 13364.0, 13342.0, 13331.0, 13359.0, 13322.0, 13250.0, 13129.0], [13577.0, 13640.0, 13705.0, 13741.0, 13791.0, 13757.0, 13644.0, 13648.0, 13655.0, 13605.0, 13592.0, 13594.0, 13654.0, 13542.0, 13431.0, 13413.0, 13379.0, 13329.0, 13340.0, 13257.0, 13253.0, 13124.0], [13464.0, 13531.0, 13635.0, 13750.0, 13739.0, 13715.0, 13687.0, 13722.0, 13704.0, 13598.0, 13578.0, 13628.0, 13579.0, 13483.0, 13481.0, 13479.0, 13422.0, 13348.0, 13268.0, 13237.0, 13240.0, 13196.0], [13414.0, 13476.0, 13533.0, 13676.0, 13711.0, 13718.0, 13744.0, 13731.0, 13676.0, 13622.0, 13541.0, 13550.0, 13431.0, 13368.0, 13377.0, 13381.0, 13320.0, 13220.0, 13205.0, 13266.0, 13231.0, 13214.0], [13325.0, 13383.0, 13472.0, 13602.0, 13635.0, 13637.0, 13805.0, 13772.0, 13676.0, 13657.0, 13444.0, 13276.0, 13264.0, 13213.0, 13198.0, 13231.0, 13111.0, 13087.0, 13201.0, 13250.0, 13200.0, 13220.0], [13196.0, 13251.0, 13374.0, 13490.0, 13570.0, 13674.0, 13757.0, 13794.0, 13704.0, 13596.0, 13402.0, 13190.0, 13151.0, 13220.0, 13281.0, 13214.0, 13096.0, 13157.0, 13235.0, 13192.0, 13214.0, 13287.0], [13231.0, 13142.0, 13288.0, 13466.0, 13527.0, 13591.0, 13657.0, 13728.0, 13655.0, 13592.0, 13366.0, 13181.0, 13192.0, 13218.0, 13292.0, 13222.0, 13190.0, 13251.0, 13194.0, 13205.0, 13224.0, 13235.0], [13231.0, 13172.0, 13244.0, 13414.0, 13502.0, 13550.0, 13555.0, 13637.0, 13641.0, 13489.0, 13309.0, 13268.0, 13227.0, 13257.0, 13276.0, 13268.0, 13222.0, 13200.0, 13151.0, 13190.0, 13270.0, 13263.0], [13144.0, 13162.0, 13233.0, 13287.0, 13389.0, 13453.0, 13427.0, 13544.0, 13618.0, 13372.0, 13259.0, 13327.0, 13242.0, 13213.0, 13203.0, 13198.0, 13144.0, 13105.0, 13138.0, 13126.0, 13192.0, 13290.0], [13105.0, 13049.0, 13199.0, 13277.0, 13361.0, 13416.0, 13500.0, 13637.0, 13520.0, 13211.0, 13081.0, 13140.0, 13175.0, 13159.0, 13031.0, 13135.0, 13153.0, 13159.0, 13183.0, 13127.0, 13207.0, 13279.0], [13112.0, 13114.0, 13133.0, 13290.0, 13435.0, 13459.0, 13585.0, 13637.0, 13381.0, 13157.0, 13029.0, 13112.0, 13151.0, 13137.0, 13012.0, 13114.0, 13172.0, 13163.0, 13196.0, 13222.0, 13231.0, 13341.0], [13211.0, 13227.0, 13277.0, 13311.0, 13414.0, 13479.0, 13585.0, 13526.0, 13498.0, 13314.0, 13205.0, 13172.0, 13164.0, 13037.0, 13005.0, 13113.0, 13088.0, 13155.0, 13298.0, 13266.0, 13215.0, 13300.0], [13201.0, 13164.0, 13268.0, 13257.0, 13329.0, 13433.0, 13589.0, 13463.0, 13518.0, 13390.0, 13285.0, 13192.0, 13187.0, 13109.0, 12999.0, 13046.0, 13101.0, 13161.0, 13263.0, 13220.0, 13185.0, 13263.0], [13161.0, 13018.0, 13053.0, 13250.0, 13301.0, 13420.0, 13515.0, 13492.0, 13502.0, 13415.0, 13290.0, 13196.0, 13177.0, 13094.0, 13062.0, 13014.0, 13037.0, 13094.0, 13172.0, 13157.0, 13148.0, 13220.0], [12994.0, 12994.0, 12946.0, 13086.0, 13264.0, 13372.0, 13427.0, 13502.0, 13478.0, 13411.0, 13379.0, 13300.0, 13259.0, 13213.0, 13237.0, 13105.0, 13048.0, 13009.0, 13127.0, 13085.0, 13090.0, 13089.0], [12901.0, 12951.0, 12922.0, 12970.0, 13183.0, 13326.0, 13303.0, 13394.0, 13413.0, 13359.0, 13359.0, 13346.0, 13359.0, 13242.0, 13203.0, 13046.0, 12990.0, 12953.0, 12970.0, 13003.0, 13000.0, 12918.0]], "red": [[12441.0, 12423.0, 12462.0, 12412.0, 12444.0, 12521.0, 12504.0, 12542.0, 12555.0, 12528.0, 12527.0, 12451.0, 12418.0, 12406.0, 12300.0, 12256.0, 12207.0, 12104.0, 11937.0, 11947.0, 12021.0, 11981.0], [12507.0, 12441.0, 12460.0, 12463.0, 12493.0, 12527.0, 12591.0, 12595.0, 12561.0, 12561.0, 12533.0, 12486.0, 12441.0, 12469.0, 12275.0, 12070.0, 12057.0, 12009.0, 11906.0, 12007.0, 12011.0, 12004.0], [12561.0, 12476.0, 12401.0, 12490.0, 12513.0, 12530.0, 12575.0, 12626.0, 12533.0, 12544.0, 12496.0, 12513.0, 12462.0, 12463.0, 12241.0, 12085.0, 12073.0, 12071.0, 12015.0, 11975.0, 11965.0, 11979.0], [12547.0, 12497.0, 12421.0, 12528.0, 12514.0, 12602.0, 12532.0, 12592.0, 12567.0, 12463.0, 12421.0, 12490.0, 12465.0, 12429.0, 12183.0, 11992.0, 12146.0, 12185.0, 12070.0, 12042.0, 12023.0, 11986.0], [12538.0, 12530.0, 12493.0, 12586.0, 12578.0, 12556.0, 12532.0, 12504.0, 12472.0, 12402.0, 12410.0, 12476.0, 12493.0, 12435.0, 12193.0, 12123.0, 12235.0, 12214.0, 12132.0, 12137.0, 12040.0, 12017.0], [12505.0, 12507.0, 12485.0, 12578.0, 12605.0, 12535.0, 12500.0, 12421.0, 12396.0, 12412.0, 12385.0, 12431.0, 12466.0, 12421.0, 12266.0, 12160.0, 12205.0, 12191.0, 12197.0, 12129.0, 12040.0, 11981.0], [12468.0, 12446.0, 12479.0, 12567.0, 12516.0, 12514.0, 12474.0, 12421.0, 12409.0, 12401.0, 12455.0, 12426.0, 12469.0, 12348.0, 12235.0, 12222.0, 12235.0, 12157.0, 12210.0, 12189.0, 12043.0, 11990.0], [12370.0, 12401.0, 12469.0, 12572.0, 12598.0, 12558.0, 12518.0, 12463.0, 12412.0, 12359.0, 12427.0, 12392.0, 12421.0, 12343.0, 12269.0, 12227.0, 12231.0, 12147.0, 12126.0, 12189.0, 12087.0, 12001.0], [12322.0, 12295.0, 12388.0, 12521.0, 12550.0, 12455.0, 12480.0, 12539.0, 12474.0, 12392.0, 12314.0, 12371.0, 12378.0, 12294.0, 12339.0, 12329.0, 12236.0, 12146.0, 12102.0, 12149.0, 12081.0, 12001.0], [12217.0, 12276.0, 12312.0, 12404.0, 12460.0, 12542.0, 12567.0, 12564.0, 12532.0, 12435.0, 12364.0, 12331.0, 12277.0, 12222.0, 12207.0, 12230.0, 12186.0, 12118.0, 12102.0, 12091.0, 12067.0, 12042.0], [12084.0, 12171.0, 12242.0, 12334.0, 12401.0, 12504.0, 12578.0, 12602.0, 12494.0, 12421.0, 12390.0, 12213.0, 12144.0, 12091.0, 12087.0, 12118.0, 12046.0, 11981.0, 12042.0, 12043.0, 12079.0, 12056.0], [11940.0, 12034.0, 12133.0, 12336.0, 12340.0, 12441.0, 12546.0, 12597.0, 12511.0, 12449.0, 12340.0, 12168.0, 12000.0, 12053.0, 12119.0, 12105.0, 12011.0, 12012.0, 12071.0, 12090.0, 12104.0, 12121.0], [11989.0, 11933.0, 12074.0, 12311.0, 12270.0, 12373.0, 12451.0, 12569.0, 12494.0, 12406.0, 12225.0, 12029.0, 12026.0, 12118.0, 12155.0, 12121.0, 12062.0, 12065.0, 12048.0, 12068.0, 12119.0, 12121.0], [12020.0, 11917.0, 12023.0, 12194.0, 12273.0, 12326.0, 12384.0, 12525.0, 12476.0, 12300.0, 12183.0, 12082.0, 12032.0, 12065.0, 12098.0, 12043.0, 12093.0, 12043.0, 12018.0, 12004.0, 12112.0, 12110.0], [11967.0, 11962.0, 11989.0, 12071.0, 12203.0, 12272.0, 12272.0, 12370.0, 12438.0, 12241.0, 12129.0, 12152.0, 12039.0, 12021.0, 12029.0, 11947.0, 11997.0, 12014.0, 11983.0, 12040.0, 12095.0, 12106.0], [11884.0, 11880.0, 11951.0, 12094.0, 12127.0, 12269.0, 12295.0, 12331.0, 12367.0, 12099.0, 11950.0, 12004.0, 11993.0, 12007.0, 11948.0, 11973.0, 11976.0, 12007.0, 11989.0, 11965.0, 12067.0, 12109.0], [11866.0, 11902.0, 11978.0, 12113.0, 12168.0, 12289.0, 12368.0, 12418.0, 12259.0, 12020.0, 11914.0, 11995.0, 11992.0, 11895.0, 11844.0, 11934.0, 11986.0, 12012.0, 12070.0, 12023.0, 12084.0, 12140.0], [11937.0, 11986.0, 11987.0, 12031.0, 12178.0, 12286.0, 12382.0, 12412.0, 12320.0, 12166.0, 12025.0, 12028.0, 12012.0, 11950.0, 11835.0, 11864.0, 11937.0, 12004.0, 12107.0, 12050.0, 12095.0, 12171.0], [11975.0, 11995.0, 11998.0, 12034.0, 12144.0, 12286.0, 12350.0, 12362.0, 12379.0, 12275.0, 12070.0, 12029.0, 11990.0, 11900.0, 11914.0, 11825.0, 11939.0, 11972.0, 12020.0, 12087.0, 12107.0, 12106.0], [11930.0, 11936.0, 11937.0, 12015.0, 12138.0, 12230.0, 12275.0, 12357.0, 12426.0, 12259.0, 12126.0, 12029.0, 12070.0, 11969.0, 11801.0, 11816.0, 11944.0, 11955.0, 11994.0, 12011.0, 11972.0, 12026.0], [11819.0, 11805.0, 11790.0, 11836.0, 12094.0, 12165.0, 12242.0, 12314.0, 12427.0, 12314.0, 12208.0, 12095.0, 12091.0, 12040.0, 11976.0, 11973.0, 11914.0, 11885.0, 11906.0, 11919.0, 11910.0, 11928.0], [11755.0, 11710.0, 11723.0, 11799.0, 12035.0, 12109.0, 12124.0, 12174.0, 12253.0, 12227.0, 12151.0, 12193.0, 12203.0, 12081.0, 11972.0, 11889.0, 11875.0, 11813.0, 11804.0, 11824.0, 11850.0, 11807.0]], "blue": [[15072.0, 15103.0, 15007.0, 14985.0, 15075.0, 15077.0, 15091.0, 15122.0, 15144.0, 15101.0, 15118.0, 14985.0, 14923.0, 14962.0, 14827.0, 14635.0, 14651.0, 14629.0, 14433.0, 14480.0, 14561.0, 14508.0], [15165.0, 15103.0, 15025.0, 15028.0, 15120.0, 15187.0, 15212.0, 15181.0, 15163.0, 15103.0, 15085.0, 15017.0, 14979.0, 14977.0, 14768.0, 14541.0, 14631.0, 14469.0, 14392.0, 14474.0, 14471.0, 14516.0], [15232.0, 15113.0, 15034.0, 15101.0, 15169.0, 15187.0, 15161.0, 15099.0, 15091.0, 15083.0, 15148.0, 15085.0, 15032.0, 15007.0, 14655.0, 14539.0, 14676.0, 14553.0, 14539.0, 14576.0, 14523.0, 14533.0], [15105.0, 15056.0, 15085.0, 15118.0, 15109.0, 15175.0, 15220.0, 15142.0, 15009.0, 14966.0, 15036.0, 14985.0, 15140.0, 14999.0, 14627.0, 14631.0, 14766.0, 14705.0, 14643.0, 14658.0, 14606.0, 14564.0], [15115.0, 15136.0, 15124.0, 15144.0, 15089.0, 15103.0, 15083.0, 15111.0, 15019.0, 14919.0, 14974.0, 15017.0, 15112.0, 14864.0, 14707.0, 14772.0, 14790.0, 14750.0, 14688.0, 14664.0, 14627.0, 14523.0], [15113.0, 15111.0, 15150.0, 15205.0, 15173.0, 15154.0, 15081.0, 14987.0, 14960.0, 14954.0, 15001.0, 15017.0, 14987.0, 14858.0, 14760.0, 14772.0, 14807.0, 14717.0, 14705.0, 14713.0, 14609.0, 14533.0], [15036.0, 15075.0, 15118.0, 15220.0, 15183.0, 15150.0, 15087.0, 15044.0, 15001.0, 14981.0, 15017.0, 15026.0, 14997.0, 14837.0, 14858.0, 14768.0, 14766.0, 14666.0, 14692.0, 14711.0, 14602.0, 14578.0], [14980.0, 15066.0, 15128.0, 15095.0, 15091.0, 15140.0, 15097.0, 15052.0, 15083.0, 14970.0, 14985.0, 15024.0, 15052.0, 14854.0, 14889.0, 14811.0, 14723.0, 14723.0, 14772.0, 14651.0, 14557.0, 14559.0], [14899.0, 14931.0, 14993.0, 15111.0, 15097.0, 15081.0, 15126.0, 15058.0, 15066.0, 14979.0, 15005.0, 14962.0, 14962.0, 14921.0, 14864.0, 14852.0, 14748.0, 14797.0, 14649.0, 14578.0, 14623.0, 14541.0], [14823.0, 14882.0, 14929.0, 15093.0, 15058.0, 15111.0, 15150.0, 15144.0, 15095.0, 14985.0, 14927.0, 14866.0, 14807.0, 14727.0, 14743.0, 14776.0, 14682.0, 14660.0, 14615.0, 14623.0, 14633.0, 14604.0], [14614.0, 14780.0, 14948.0, 15007.0, 15097.0, 15138.0, 15169.0, 15148.0, 15028.0, 14880.0, 14774.0, 14688.0, 14563.0, 14553.0, 14615.0, 14604.0, 14543.0, 14443.0, 14517.0, 14641.0, 14576.0, 14680.0], [14608.0, 14641.0, 14770.0, 14917.0, 14923.0, 14948.0, 15163.0, 15187.0, 15005.0, 14930.0, 14772.0, 14574.0, 14492.0, 14549.0, 14670.0, 14574.0, 14502.0, 14514.0, 14453.0, 14517.0, 14578.0, 14645.0], [14700.0, 14664.0, 14735.0, 14909.0, 14932.0, 14968.0, 15114.0, 15216.0, 15075.0, 14899.0, 14608.0, 14492.0, 14606.0, 14621.0, 14645.0, 14578.0, 14557.0, 14623.0, 14514.0, 14484.0, 14570.0, 14600.0], [14602.0, 14623.0, 14731.0, 14842.0, 14862.0, 14844.0, 14891.0, 15071.0, 14985.0, 14782.0, 14631.0, 14576.0, 14617.0, 14598.0, 14555.0, 14588.0, 14549.0, 14486.0, 14463.0, 14502.0, 14609.0, 14635.0], [14520.0, 14619.0, 14639.0, 14625.0, 14750.0, 14840.0, 14850.0, 15040.0, 14958.0, 14617.0, 14572.0, 14680.0, 14633.0, 14584.0, 14535.0, 14490.0, 14476.0, 14502.0, 14418.0, 14488.0, 14668.0, 14656.0], [14533.0, 14527.0, 14551.0, 14600.0, 14702.0, 14848.0, 14972.0, 15075.0, 14850.0, 14416.0, 14371.0, 14582.0, 14561.0, 14506.0, 14492.0, 14445.0, 14467.0, 14508.0, 14478.0, 14555.0, 14672.0, 14635.0], [14553.0, 14502.0, 14594.0, 14760.0, 14762.0, 14893.0, 14934.0, 14983.0, 14760.0, 14459.0, 14461.0, 14529.0, 14514.0, 14386.0, 14457.0, 14459.0, 14517.0, 14574.0, 14590.0, 14623.0, 14629.0, 14690.0], [14688.0, 14645.0, 14641.0, 14776.0, 14750.0, 14913.0, 15003.0, 14934.0, 14860.0, 14647.0, 14596.0, 14602.0, 14600.0, 14447.0, 14437.0, 14478.0, 14523.0, 14525.0, 14615.0, 14664.0, 14637.0, 14729.0], [14655.0, 14615.0, 14561.0, 14643.0, 14774.0, 14952.0, 14901.0, 14952.0, 14911.0, 14707.0, 14572.0, 14510.0, 14494.0, 14476.0, 14422.0, 14443.0, 14508.0, 14457.0, 14553.0, 14566.0, 14602.0, 14647.0], [14545.0, 14453.0, 14416.0, 14613.0, 14772.0, 14934.0, 14944.0, 14954.0, 14940.0, 14774.0, 14660.0, 14590.0, 14559.0, 14535.0, 14457.0, 14420.0, 14494.0, 14461.0, 14541.0, 14429.0, 14468.0, 14472.0], [14353.0, 14357.0, 14416.0, 14496.0, 14662.0, 14807.0, 14786.0, 14772.0, 14860.0, 14776.0, 14733.0, 14666.0, 14641.0, 14529.0, 14431.0, 14449.0, 14375.0, 14390.0, 14425.0, 14375.0, 14439.0, 14341.0], [14248.0, 14296.0, 14412.0, 14484.0, 14649.0, 14690.0, 14639.0, 14815.0, 14737.0, 14660.0, 14633.0, 14660.0, 14651.0, 14623.0, 14494.0, 14441.0, 14343.0, 14339.0, 14345.0, 14349.0, 14355.0, 14251.0]]}, "axes": {"time": "2016-08-12T07:57:10"}, "classifiers": {"tile": "37MBU"}, "context": "time_lat_lon"}, {"indexAxes": [["latitude", [-0.9594591856002808, -0.9593690633773804, -0.95927894115448, -0.9591888189315796, -0.9590986967086792, -0.9590085744857788, -0.9589184522628784, -0.958828330039978, -0.9587382078170776, -0.9586480855941772, -0.9585579633712769, -0.9584679007530212, -0.9583777785301208, -0.9582876563072205, -0.9581975340843201, -0.9581074118614197, -0.9580172896385193, -0.9579271674156189, -0.9578370451927185, -0.9577469229698181, -0.9576568007469177, -0.9575666785240173]], ["longitude", [36.62022399902344, 36.62031555175781, 36.62040710449219, 36.6204948425293, 36.62058639526367, 36.62067794799805, 36.620765686035156, 36.62085723876953, 36.62094497680664, 36.621036529541016, 36.62112808227539, 36.6212158203125, 36.621307373046875, 36.62139892578125, 36.62148666381836, 36.621578216552734, 36.621665954589844, 36.62175750732422, 36.621849060058594, 36.6219367980957, 36.62202835083008, 36.62211990356445]]], "data": {"green": [[475.0, 521.0, 360.0, 408.0, 544.0, 588.0, 576.0, 582.0, 485.0, 459.0, 444.0, 444.0, 274.0, 202.0, 256.0, 244.0, 275.0, 244.0, 293.0, 550.0, 782.0, 752.0], [500.0, 662.0, 637.0, 581.0, 555.0, 441.0, 450.0, 506.0, 613.0, 657.0, 585.0, 589.0, 423.0, 202.0, 214.0, 256.0, 374.0, 363.0, 283.0, 428.0, 633.0, 534.0], [595.0, 713.0, 701.0, 635.0, 542.0, 395.0, 340.0, 491.0, 640.0, 659.0, 580.0, 496.0, 417.0, 276.0, 289.0, 262.0, 274.0, 245.0, 219.0, 293.0, 376.0, 237.0], [622.0, 707.0, 746.0, 691.0, 573.0, 505.0, 528.0, 530.0, 615.0, 466.0, 349.0, 260.0, 258.0, 311.0, 398.0, 293.0, 239.0, 196.0, 237.0, 304.0, 335.0, 295.0], [592.0, 721.0, 703.0, 738.0, 738.0, 583.0, 617.0, 536.0, 555.0, 392.0, 228.0, 210.0, 288.0, 452.0, 469.0, 332.0, 284.0, 229.0, 264.0, 334.0, 355.0, 388.0], [547.0, 636.0, 688.0, 678.0, 682.0, 606.0, 658.0, 588.0, 455.0, 288.0, 176.0, 174.0, 309.0, 415.0, 305.0, 206.0, 270.0, 291.0, 253.0, 258.0, 210.0, 328.0], [530.0, 530.0, 605.0, 663.0, 616.0, 610.0, 666.0, 637.0, 364.0, 126.0, 147.0, 131.0, 201.0, 269.0, 253.0, 274.0, 282.0, 276.0, 274.0, 353.0, 299.0, 459.0], [577.0, 584.0, 570.0, 528.0, 607.0, 730.0, 631.0, 631.0, 405.0, 184.0, 164.0, 286.0, 178.0, 197.0, 238.0, 327.0, 282.0, 228.0, 295.0, 460.0, 535.0, 529.0], [530.0, 484.0, 468.0, 559.0, 758.0, 761.0, 705.0, 639.0, 478.0, 321.0, 281.0, 426.0, 331.0, 284.0, 280.0, 325.0, 286.0, 222.0, 257.0, 431.0, 582.0, 574.0], [540.0, 414.0, 433.0, 553.0, 704.0, 727.0, 725.0, 622.0, 502.0, 482.0, 453.0, 424.0, 393.0, 335.0, 280.0, 319.0, 348.0, 226.0, 232.0, 309.0, 440.0, 562.0], [643.0, 521.0, 489.0, 588.0, 679.0, 630.0, 595.0, 504.0, 504.0, 540.0, 544.0, 536.0, 443.0, 366.0, 348.0, 460.0, 582.0, 435.0, 348.0, 237.0, 297.0, 355.0], [545.0, 440.0, 488.0, 598.0, 610.0, 597.0, 597.0, 343.0, 451.0, 542.0, 509.0, 387.0, 470.0, 488.0, 439.0, 542.0, 623.0, 576.0, 414.0, 261.0, 272.0, 324.0], [399.0, 418.0, 527.0, 565.0, 583.0, 669.0, 553.0, 378.0, 446.0, 477.0, 544.0, 453.0, 494.0, 517.0, 492.0, 418.0, 482.0, 532.0, 433.0, 375.0, 259.0, 257.0], [322.0, 473.0, 603.0, 610.0, 641.0, 677.0, 410.0, 386.0, 490.0, 494.0, 467.0, 440.0, 498.0, 428.0, 397.0, 383.0, 354.0, 459.0, 435.0, 427.0, 245.0, 243.0], [545.0, 537.0, 622.0, 748.0, 727.0, 629.0, 520.0, 483.0, 533.0, 601.0, 593.0, 521.0, 494.0, 312.0, 246.0, 258.0, 223.0, 321.0, 333.0, 338.0, 247.0, 272.0], [594.0, 532.0, 549.0, 710.0, 771.0, 635.0, 490.0, 568.0, 675.0, 649.0, 612.0, 572.0, 481.0, 235.0, 239.0, 273.0, 343.0, 436.0, 530.0, 373.0, 238.0, 247.0], [679.0, 621.0, 566.0, 630.0, 700.0, 661.0, 581.0, 712.0, 741.0, 653.0, 589.0, 611.0, 460.0, 307.0, 370.0, 463.0, 531.0, 517.0, 525.0, 434.0, 265.0, 251.0], [662.0, 617.0, 565.0, 650.0, 529.0, 407.0, 482.0, 655.0, 656.0, 600.0, 569.0, 551.0, 411.0, 380.0, 533.0, 630.0, 546.0, 492.0, 492.0, 503.0, 430.0, 354.0], [612.0, 561.0, 567.0, 617.0, 407.0, 312.0, 428.0, 517.0, 583.0, 540.0, 443.0, 327.0, 323.0, 458.0, 642.0, 682.0, 529.0, 535.0, 585.0, 480.0, 488.0, 484.0], [606.0, 554.0, 569.0, 526.0, 338.0, 322.0, 521.0, 513.0, 639.0, 505.0, 414.0, 311.0, 466.0, 568.0, 617.0, 570.0, 537.0, 605.0, 583.0, 538.0, 474.0, 478.0], [643.0, 571.0, 523.0, 441.0, 297.0, 386.0, 479.0, 560.0, 1429.0, 843.0, 447.0, 511.0, 592.0, 507.0, 530.0, 566.0, 560.0, 525.0, 516.0, 616.0, 560.0, 525.0], [599.0, 566.0, 443.0, 303.0, 224.0, 505.0, 532.0, 648.0, 756.0, 378.0, 383.0, 552.0, 581.0, 499.0, 507.0, 599.0, 642.0, 566.0, 465.0, 546.0, 511.0, 517.0]], "red": [[452.0, 313.0, 245.0, 244.0, 550.0, 753.0, 466.0, 233.0, 180.0, 183.0, 183.0, 178.0, 132.0, 88.0, 117.0, 137.0, 164.0, 173.0, 178.0, 639.0, 844.0, 748.0], [431.0, 520.0, 464.0, 462.0, 626.0, 623.0, 307.0, 250.0, 340.0, 304.0, 211.0, 202.0, 135.0, 140.0, 108.0, 159.0, 239.0, 270.0, 135.0, 412.0, 706.0, 719.0], [484.0, 530.0, 477.0, 553.0, 706.0, 428.0, 215.0, 371.0, 553.0, 431.0, 256.0, 209.0, 128.0, 130.0, 162.0, 152.0, 161.0, 168.0, 105.0, 200.0, 305.0, 327.0], [543.0, 547.0, 477.0, 532.0, 691.0, 476.0, 457.0, 534.0, 534.0, 393.0, 171.0, 118.0, 82.0, 120.0, 193.0, 149.0, 120.0, 121.0, 99.0, 174.0, 154.0, 161.0], [522.0, 584.0, 538.0, 569.0, 641.0, 494.0, 510.0, 520.0, 387.0, 227.0, 94.0, 55.0, 89.0, 176.0, 215.0, 145.0, 106.0, 99.0, 126.0, 156.0, 183.0, 181.0], [538.0, 582.0, 538.0, 615.0, 697.0, 643.0, 713.0, 524.0, 276.0, 124.0, 73.0, 83.0, 133.0, 160.0, 94.0, 89.0, 116.0, 114.0, 113.0, 125.0, 145.0, 229.0], [575.0, 491.0, 483.0, 705.0, 671.0, 866.0, 945.0, 761.0, 300.0, 83.0, 63.0, 85.0, 102.0, 95.0, 66.0, 71.0, 104.0, 95.0, 106.0, 119.0, 217.0, 494.0], [544.0, 481.0, 526.0, 492.0, 736.0, 973.0, 948.0, 858.0, 443.0, 138.0, 107.0, 115.0, 103.0, 100.0, 98.0, 90.0, 71.0, 66.0, 104.0, 174.0, 393.0, 608.0], [445.0, 332.0, 404.0, 497.0, 845.0, 955.0, 907.0, 895.0, 494.0, 214.0, 158.0, 201.0, 216.0, 139.0, 

## Cloud Cover

Cloud coverage is calculated on a per-tile, per-timestamp basis and stored in the `cloudy_pixels_percentage` variable. Because the coverage is on a per-tile basis, there are no latitude or longitude axes, only a time axis. Let's grab the cloud cover data and associate it with our RGB values from our original query.

In [12]:
# Use the same params query, but update 'var' to request cloud percentage
params['var'] = 'cloudy_pixels_percentage'
print(params, '\n') # output to refresh our memory

# Request the data and store in a dataframe
ds_rgb_clouds = api_point_query(ds_rgb_id, params)
df_clouds = pd.io.json.json_normalize(ds_rgb_clouds['entries'])

print(df_clouds.count())
df_clouds.head()

{'time_order': 'desc', 'var': 'cloudy_pixels_percentage', 'max_count': 'true', 'nearest': 'true', 'lon': 36.62117917585404, 'count': 5, 'lat': -0.9584909201199898, 'apikey': '535871ea3d554497843ab250a497e626'}

axes.time                        641
classifiers.tile                 641
context                          641
data.cloudy_pixels_percentage    641
dtype: int64

             axes.time classifiers.tile context  data.cloudy_pixels_percentage
0  2016-08-09T07:49:17            37MEV    time                      88.624298
1  2016-07-30T07:43:34            37MEV    time                       0.213200
2  2016-07-20T07:49:17            37MEV    time                      15.894700
3  2016-08-09T07:42:40            37NFD    time                      51.823601
4  2016-07-30T07:43:34            37NFD    time                      24.503901

In order to merge our RGB and cloud coverage datasets we'll first index both by time and tile.

In [13]:
# Index rgb dataframe by time and tile, sort in descending order
df_tt = df.set_index(['axes.time','classifiers.tile']).sort_index(ascending=False)
print(df_tt.count())
df_tt.head()

axes.latitude     17
axes.longitude    17
context           17
data.blue         10
data.green        10
data.red          10
dtype: int64

                                      axes.latitude  axes.longitude  \
axes.time           classifiers.tile
2016-08-15T08:08:34 36MZE                 -0.958516       36.621220
                    36MZD                 -0.958452       36.621212
2016-08-12T07:57:10 37MBV                 -0.958492       36.621159
                    37MBU                 -0.958468       36.621216
                    36MZE                 -0.958516       36.621220

                                           context  data.blue  data.green  \
axes.time           classifiers.tile
2016-08-15T08:08:34 36MZE             time_lat_lon        NaN         NaN
                    36MZD             time_lat_lon        NaN         NaN
2016-08-12T07:57:10 37MBV             time_lat_lon    14153.0     12845.0
                    37MBU             time_lat_lon    14574.0     13190.0
                    36MZE             time_lat_lon    13241.0     12131.0

                                      data.red
axes.time           classifiers.tile
2016-08-15T08:08:34 36MZE                  NaN
                    36MZD                  NaN
2016-08-12T07:57:10 37MBV              11983.0
                    37MBU              12168.0
                    36MZE              11451.0

In [14]:
# Index cloud coverage dataframe by time and tile, sort in descending order
df_clouds_tt = df_clouds.set_index(['axes.time','classifiers.tile']).sort_index(ascending=False)
print(df_clouds_tt.count())
df_clouds_tt.head()

context                          641
data.cloudy_pixels_percentage    641
dtype: int64

                                     context  data.cloudy_pixels_percentage
axes.time           classifiers.tile
2016-08-15T08:08:34 36MZE               time                      10.818700
                    36MZD               time                      55.430099
                    36MZC               time                      61.775501
                    36MYE               time                       7.707000
                    36MYD               time                       6.394300

In [15]:
# Concatenate the RGB and cloud percentage dataframes using an inner join 
df_rgbc = pd.concat([df_tt, df_clouds_tt], axis=1, join='inner')

# Drop the context columns to clean up the dataframe
df_rgbc.drop(['context'], axis=1, inplace=True)

# Sort by descending time
df_rgbc.sort_index(ascending=False, inplace=True)

print(df_rgbc.count())
df_rgbc.head(10)

axes.latitude                    17
axes.longitude                   17
data.blue                        10
data.green                       10
data.red                         10
data.cloudy_pixels_percentage    17
dtype: int64

                                      axes.latitude  axes.longitude  \
axes.time           classifiers.tile
2016-08-15T08:08:34 36MZE                 -0.958516       36.621220
                    36MZD                 -0.958452       36.621212
2016-08-12T07:57:10 37MBV                 -0.958492       36.621159
                    37MBU                 -0.958468       36.621216
                    36MZE                 -0.958516       36.621220
                    36MZD                 -0.958452       36.621212
2016-08-05T08:03:48 36MZE                 -0.958516       36.621220
                    36MZD                 -0.958452       36.621212
2016-08-02T07:55:56 37MBV                 -0.958492       36.621159
                    37MBU                 -0.958468       36.621216

                                      data.blue  data.green  data.red  \
axes.time           classifiers.tile
2016-08-15T08:08:34 36MZE                   NaN         NaN       NaN
                    36MZD                   NaN         NaN       NaN
2016-08-12T07:57:10 37MBV               14153.0     12845.0   11983.0
                    37MBU               14574.0     13190.0   12168.0
                    36MZE               13241.0     12131.0   11451.0
                    36MZD               14929.0     13441.0   12344.0
2016-08-05T08:03:48 36MZE                   NaN         NaN       NaN
                    36MZD                   NaN         NaN       NaN
2016-08-02T07:55:56 37MBV                 237.0       470.0     512.0
                    37MBU                 283.0       387.0     385.0

                                      data.cloudy_pixels_percentage
axes.time           classifiers.tile
2016-08-15T08:08:34 36MZE                                 10.818700
                    36MZD                                 55.430099
2016-08-12T07:57:10 37MBV                                 58.606201
                    37MBU                                 92.040802
                    36MZE                                 34.561001
                    36MZD                                 73.080704
2016-08-05T08:03:48 36MZE                                 99.553596
                    36MZD                                 32.312599
2016-08-02T07:55:56 37MBV                                  4.137100
                    37MBU                                  0.000000

The dataframe `df_rgbc` now contains RGB and cloud coverage data. We can again use the `dropna` method to remove rows with `NaN` values for RGB.

In [16]:
df_rgbc_clean = df_rgbc.dropna()
print(df_rgbc_clean.count())
df_rgbc_clean.head()

axes.latitude                    10
axes.longitude                   10
data.blue                        10
data.green                       10
data.red                         10
data.cloudy_pixels_percentage    10
dtype: int64

                                      axes.latitude  axes.longitude  \
axes.time           classifiers.tile
2016-08-12T07:57:10 37MBV                 -0.958492       36.621159
                    37MBU                 -0.958468       36.621216
                    36MZE                 -0.958516       36.621220
                    36MZD                 -0.958452       36.621212
2016-08-02T07:55:56 37MBV                 -0.958492       36.621159

                                      data.blue  data.green  data.red  \
axes.time           classifiers.tile
2016-08-12T07:57:10 37MBV               14153.0     12845.0   11983.0
                    37MBU               14574.0     13190.0   12168.0
                    36MZE               13241.0     12131.0   11451.0
                    36MZD               14929.0     13441.0   12344.0
2016-08-02T07:55:56 37MBV                 237.0       470.0     512.0

                                      data.cloudy_pixels_percentage
axes.time           classifiers.tile
2016-08-12T07:57:10 37MBV                                 58.606201
                    37MBU                                 92.040802
                    36MZE                                 34.561001
                    36MZD                                 73.080704
2016-08-02T07:55:56 37MBV                                  4.137100

In [17]:
# We can also use groupby to determine statistics over all available timestamps within each unique point.
df_rgbc_clean.groupby(['axes.latitude','axes.longitude']).describe()

                                       data.blue  \
axes.latitude axes.longitude
-0.958516     36.621220      count      2.000000
                             mean    6704.000000
                             std     9244.714057
                             min      167.000000
                             25%     3435.500000
                             50%     6704.000000
                             75%     9972.500000
                             max    13241.000000
-0.958492     36.621159      count      3.000000
                             mean    4881.666667
                             std     8029.215238
                             min      237.000000
                             25%      246.000000
                             50%      255.000000
                             75%     7204.000000
                             max    14153.000000
-0.958468     36.621216      count      3.000000
                             mean    5065.666667
                             std     8234.507534
                             min      283.000000
                             25%      311.500000
                             50%      340.000000
                             75%     7457.000000
                             max    14574.000000
-0.958452     36.621212      count      2.000000
                             mean    7639.000000
                             std    10309.616870
                             min      349.000000
                             25%     3994.000000
                             50%     7639.000000
                             75%    11284.000000
                             max    14929.000000

                                    data.cloudy_pixels_percentage  \
axes.latitude axes.longitude
-0.958516     36.621220      count                       2.000000
                             mean                       19.514601
                             std                        21.278823
                             min                         4.468200
                             25%                        11.991400
                             50%                        19.514601
                             75%                        27.037801
                             max                        34.561001
-0.958492     36.621159      count                       3.000000
                             mean                       23.599500
                             std                        30.379923
                             min                         4.137100
                             25%                         6.096150
                             50%                         8.055200
                             75%                        33.330700
                             max                        58.606201
-0.958468     36.621216      count                       3.000000
                             mean                       32.409834
                             std                        51.707059
                             min                         0.000000
                             25%                         2.594350
                             50%                         5.188700
                             75%                        48.614751
                             max                        92.040802
-0.958452     36.621212      count                       2.000000
                             mean                       36.540352
                             std                        51.675861
                             min                         0.000000
                             25%                        18.270176
                             50%                        36.540352
                             75%                        54.810528
                             max                        73.080704

                                      data.green      data.red
axes.latitude axes.longitude
-0.958516     36.621220      count      2.000000      2.000000
                             mean    6257.500000   5946.000000
                             std     8306.383359   7785.245661
                             min      384.000000    441.000000
                             25%     3320.750000   3193.500000
                             50%     6257.500000   5946.000000
                             75%     9194.250000   8698.500000
                             max    12131.000000  11451.000000
-0.958492     36.621159      count      3.000000      3.000000
                             mean    4618.333333   4318.666667
                             std     7124.588292   6637.556353
                             min      470.000000    461.000000
                             25%      505.000000    486.500000
                             50%      540.000000    512.000000
                             75%     6692.500000   6247.500000
                             max    12845.000000  11983.000000
-0.958468     36.621216      count      3.000000      3.000000
                             mean    4673.333333   4303.333333
                             std     7375.702837   6811.015514
                             min      387.000000    357.000000
                             25%      415.000000    371.000000
                             50%      443.000000    385.000000
                             75%     6816.500000   6276.500000
                             max    13190.000000  12168.000000
-0.958452     36.621212      count      2.000000      2.000000
                             mean    6938.000000   6382.000000
                             std     9196.630796   8431.541259
                             min      435.000000    420.000000
                             25%     3686.500000   3401.000000
                             50%     6938.000000   6382.000000
                             75%    10189.500000   9363.000000
                             max    13441.000000  12344.000000